name: CI

on:
    pull_request:
        branches: [main]
jobs:
    setup:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.13.1]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node-version }}
            -   name: Cache Node.js modules
                uses: actions/cache@v4
                with:
                    path: ~/.npm
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-node-
            -   name: Install Dependencies
                run: npm ci

    lint:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Install Dependencies
                run: npm ci
            -   name: Run ESLint
                run: npm run lint

    format-check:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Install Dependencies
                run: npm ci
            -   name: Run Prettier
                run: npm run format-check

    spell-check:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Install Dependencies
                run: npm ci
            -   name: Run cSpell
                run: npm run spell-check

    generate:
        needs: [lint, format-check, spell-check]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Install Dependencies
                run: npm ci
            -   name: Prerender Nuxt
                run: npx nuxi generate
